org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
fileName=FastSuite
modName=FastSuite
modGroup=dev.shadowsoffire
modid=fastsuite
author=Shadows_of_Fire
desc=Improves recipe performance through indexing.
version=7.0.0
mcVersion=26.2
javaVersion=25
loaderVersion=0.19.3
